---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: netplan
    box: ubuntu/focal64
verifier:
  name: testinfra
  lint:
    name: flake8
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      netplan:
        netplan_etc_configs:
          50-br1:
            network:
              version: 2
              bridges:
                br1:
                  addresses:
                    - 192.0.2.1/24
